services:
  app:
    build: .
    volumes:
      - ./app:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      - POSTGRES_USER=XXX
      - POSTGRES_PASSWORD=XXX
      - POSTGRES_DB=XXX
    volumes:
      - financial_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  financial_data: